name: Smoke Tests

on:
  workflow_dispatch:
  # Allow workflow to be ran via API
  repository_dispatch:
    types: [run_smoke_tests]
  schedule:
      # Once a day at 12pm EST
    - cron: '0 16 * * 1-5'
  push:
    branches: [main]

env:
  BELAY_API_URL: ${{ vars.BELAY_API_URL }}
  BELAY_API_WS_URL: ${{ vars.BELAY_API_WS_URL }}
  BELAY_API_AUTH0_CLIENT_ID: ${{ secrets.BELAY_API_AUTH0_CLIENT_ID }}
  BELAY_API_AUTH0_CLIENT_SECRET: ${{ secrets.BELAY_API_AUTH0_CLIENT_SECRET }}
  ALPACA_BASE_URL: ${{ vars.ALPACA_BASE_URL }}
  ALPACA_KEY: ${{ secrets.ALPACA_KEY }}
  ALPACA_SECRET: ${{ secrets.ALPACA_SECRET }}

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest-m

    steps:
      - uses: actions/checkout@v3

      - name: Determine the elixir version
        run: echo "ELIXIR_VERSION=$(grep -h elixir .tool-versions | awk '{ print $2 }' | awk -F - '{print $1}')" >> $GITHUB_ENV

      - name: Determine the otp version
        run: echo "OTP_VERSION=$(grep -h erlang .tool-versions | awk '{ print $2 }')" >> $GITHUB_ENV

      - name: Setup Elixir and Erlang versions
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}

      - name: Cache Mix
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ env.elixir }}-${{ env.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.elixir }}-${{ env.otp }}-

      - name: Install mix dependencies
        run: mix deps.get

      - name: Run smoke tests
        run: mix test.smoke

      - name: Notify Slack
        uses: craftech-io/slack-action@v1
        if: always()
        with:
          slack_webhook_url: ${{ secrets.SLACK_DEVELOPMENT_WEBHOOK_URL }}